export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREMENT_PRODUCT_QUANTITY = 'INCREMENT_PRODUCT_QUANTITY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const DECREMENT_PRODUCT_QUANTITY = 'DECREMENT_PRODUCT_QUANTITY';